export enum DestinationActionTriggers {
    SHUTDOWN = 'SHUTDOWN',
    STARTUP = 'STARTUP',
    OPEN_DOCUMENT = 'OPEN_DOCUMENT',
    OPEN_FOLDER = 'OPEN_FOLDER',
    OPEN_BROWSER = 'OPEN_BROWSER',
    OPEN_SETTINGS = 'OPEN_SETTINGS',
    OPEN_RUN = 'OPEN_RUN'
}