export enum DestinationActionTriggers {
    SHUTDOWN = 'SHUTDOWN',
    STARTUP = 'STARTUP',
    OPEN_DOCUMENT_RESUME = 'OPEN_DOCUMENT_RESUME',
    OPEN_FOLDER = 'OPEN_FOLDER',
    OPEN_BROWSER = 'OPEN_BROWSER',
}